# generated by datamodel-codegen:
#   filename:  shared-contracts-bundle.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class CreateJobRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    F: int = Field(..., ge=1)
    C: int = Field(..., ge=1)
    reuseSampleFile: bool | None = False


class CreateJobResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    jobId: str = Field(..., min_length=1)


class FleetView(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    W: int = Field(..., ge=0)
    inFlight: int = Field(..., ge=0)
    free: int


class InputKind(StrEnum):
    file = "file"
    partial = "partial"


class JobStatus(StrEnum):
    GENERATING = "GENERATING"
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class Status(StrEnum):
    GENERATING = "GENERATING"
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ByLevelItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: int = Field(..., ge=0)
    queued: int = Field(..., ge=0)
    inProgress: int = Field(..., ge=0)
    done: int = Field(..., ge=0)
    failed: int = Field(..., ge=0)
    total: int = Field(..., ge=0)


class TaskSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    queued: int = Field(..., ge=0)
    inProgress: int = Field(..., ge=0)
    done: int = Field(..., ge=0)
    failed: int = Field(..., ge=0)
    total: int = Field(..., ge=0)
    byLevel: list[ByLevelItem]


class InputManifestPreviewItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fileIndex: int = Field(..., ge=0)
    inputKey: str = Field(..., min_length=1)
    plannedLeafTaskId: str = Field(..., min_length=1)
    plannedLeafLevel: int = Field(..., ge=0)


class JobView(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    jobId: str = Field(..., min_length=1)
    status: Status
    F: int = Field(..., ge=1)
    C: int = Field(..., ge=1)
    reuseSampleFile: bool | None = None
    submittedAt: int = Field(..., ge=0)
    endedAt: int | None = Field(None, ge=0)
    durationMs: int | None = Field(None, ge=0)
    percent: float = Field(..., ge=0.0, le=1.0)
    reductionsRemaining: int = Field(..., ge=0)
    queuePosition: int | None = Field(None, gt=0)
    chunkSizeUsed: int | None = Field(None, gt=0)
    leafTasksTotal: int | None = Field(None, ge=0)
    leafTasksDone: int | None = Field(None, ge=0)
    readyCount: int | None = Field(None, ge=0)
    claimedCount: int | None = Field(None, ge=0)
    taskSummary: TaskSummary | None = None
    inputManifestPreview: list[InputManifestPreviewItem] | None = None
    resultUrl: AnyUrl | None = None
    error: str | None = Field(None, min_length=1)


class InputKey(RootModel[str]):
    root: str = Field(..., min_length=1)


class MergeTask(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    jobId: str = Field(..., min_length=1)
    taskId: str = Field(..., min_length=1)
    inputKind: InputKind
    level: int = Field(..., ge=0)
    inputKeys: list[InputKey] = Field(..., max_length=5, min_length=1)
    C: int = Field(..., ge=1)


class SetWorkersRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int = Field(..., ge=0)


class TaskStatus(StrEnum):
    QUEUED = "QUEUED"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    FAILED = "FAILED"


class SharedContractsBundle(
    RootModel[
        CreateJobRequest
        | CreateJobResponse
        | FleetView
        | InputKind
        | JobStatus
        | JobView
        | MergeTask
        | SetWorkersRequest
        | TaskStatus
    ]
):
    root: (
        CreateJobRequest
        | CreateJobResponse
        | FleetView
        | InputKind
        | JobStatus
        | JobView
        | MergeTask
        | SetWorkersRequest
        | TaskStatus
    ) = Field(..., title="SharedContractsBundle")
