# generated by datamodel-codegen:
#   filename:  shared-contracts-bundle.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class CreateJobRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    F: int = Field(..., ge=1)
    C: int = Field(..., ge=1)


class CreateJobResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    jobId: str = Field(..., min_length=1)


class FleetView(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    W: int = Field(..., ge=0)
    inFlight: int = Field(..., ge=0)
    free: int


class InputKind(StrEnum):
    file = "file"
    partial = "partial"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class Status(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class JobView(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    jobId: str = Field(..., min_length=1)
    status: Status
    F: int = Field(..., ge=1)
    C: int = Field(..., ge=1)
    submittedAt: int = Field(..., ge=0)
    percent: float = Field(..., ge=0.0, le=1.0)
    reductionsRemaining: int = Field(..., ge=0)
    queuePosition: int | None = Field(None, gt=0)
    resultUrl: AnyUrl | None = None
    error: str | None = Field(None, min_length=1)


class InputKey(RootModel[str]):
    root: str = Field(..., min_length=1)


class MergeTask(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    jobId: str = Field(..., min_length=1)
    taskId: str = Field(..., min_length=1)
    inputKind: InputKind
    level: int = Field(..., ge=0)
    inputKeys: list[InputKey] = Field(..., max_length=5, min_length=1)
    C: int = Field(..., ge=1)


class SetWorkersRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: int = Field(..., ge=0)


class TaskStatus(StrEnum):
    QUEUED = "QUEUED"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    FAILED = "FAILED"


class SharedContractsBundle(
    RootModel[
        CreateJobRequest
        | CreateJobResponse
        | FleetView
        | InputKind
        | JobStatus
        | JobView
        | MergeTask
        | SetWorkersRequest
        | TaskStatus
    ]
):
    root: (
        CreateJobRequest
        | CreateJobResponse
        | FleetView
        | InputKind
        | JobStatus
        | JobView
        | MergeTask
        | SetWorkersRequest
        | TaskStatus
    ) = Field(..., title="SharedContractsBundle")
